### ISSUE TITLE
Gradle build failed with test-resources : NoSuchFileException

### ISSUE THREAD

**Issue by bitxon** [micronaut-projects/micronaut-gradle-plugin#528]
### Expected Behavior

Successful build

### Actual Behaviour

Build failed with Error
```text
Execution failed for task ':internalStartTestResourcesService'.
> java.nio.file.NoSuchFileException: /Users/username/Dev/micronaut-test-resource-failed/build/test-resources/b875be46-9804-43e8-a57d-704191197d27
```

### Steps To Reproduce

1. Generate Gradle project with features that includes 'test-resources'
```yaml
applicationType: default
defaultPackage: org.experiment
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [annotation-api, app-name, assertj, gradle, hibernate-jpa, hibernate-validator, http-client, jackson-databind, java, java-application, jdbc-hikari, junit, logback, management, micronaut-build, netty-server, postgres, readme, shade, test-resources, testcontainers, yaml]
```
2.  Run `./gradlew clean build`

### Environment Information

- OS: MacOS (arm64) and Ubuntu 22 (Didn't check on windows)
- Java: openjdk version "17.0.2"
- Gradle: 7.5 (also checked on 7.4.1)
- Micronaut: 3.6.1 and 3.6.0

### Example Application

https://github.com/bitxon/micronaut-test-resource-failed

### Version

3.6.1 and 3.6.0
